### ISSUE TITLE
모달창 오버레이 클릭시 발생하는 API fetch 오류(404)

### ISSUE THREAD

**Issue by sosososoyoen** [soonmac/nexflix-clone#3]
![질문2](https://user-images.githubusercontent.com/55690712/160124088-4a7345bf-5b88-420d-ba71-f8246022f747.PNG)
![질문1](https://user-images.githubusercontent.com/55690712/160128243-88af6b62-4028-4315-8800-ac6c9b01d803.PNG)
모달창이 떠있는 상태에서 오버레이를 클릭해서 기존 화면으로 돌아가면
모달창 컴포넌트 파일에 써둔 리액트 쿼리 함수가 작동하면서 404 오류 발생함 

영상

https://user-images.githubusercontent.com/55690712/160128276-15fd689b-a846-4caf-bd86-bd9db8f95574.mp4

**Comment by malcha-coconut** [comment]
모달창에 조건을 걸었음 
영화 항목 페이지에 들어갔을 때 모달창 컴포넌트가 렌더링되도록
Slide.tsx
```javascript
  const detailMatch = useRouteMatch(`/${category}/${type}/:movieId`);
.
.
.
          {detailMatch ? (
            <AnimatePresence>
              <Modal data={data} type={type} category={category} url={url} />
            </AnimatePresence>
          ) : null}
        </>
      )}
```
